services:
  - type: web
    name: immo-eliza-api
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile.api
    dockerContext: .
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1

  - type: web
    name: immo-eliza-streamlit
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile.streamlit
    dockerContext: .
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: API_URL
        fromService:
          serviceName: immo-eliza-api
          property: host
